# Site settings
title: Copenhagen Ruby Brigade
email: copenhagen.rb@substancelab.com
description: >
  A group of Ruby enthusiasts from Copenhagen, Denmark who meet roughly every
  month to talk about Ruby, programming, and other related topics.
baseurl: ""
url: "http://copenhagenrb.dk"
twitter_username: copenhagenrb
github_username:  copenhagenrb

# Build settings
markdown: kramdown

exclude:
- README.md
