# Site settings
title: Copenhagen Ruby Brigade
email: copenhagen.rb@substancelab.com
description: > # this means to ignore newlines until "baseurl:"
  A group of Ruby enthusiasts from Copenhagen, Denmark who meet roughly every
  month to talk about Ruby, programming, and other related topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://copenhagenrb.dk" # the base hostname & protocol for your site
twitter_username: copenhagenrb
github_username:  copenhagenrb

# Build settings
markdown: kramdown
